# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui/default/DefaultMain.ui'
#
# Created: Fri Feb 19 17:40:41 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DefaultMain(object):
    def setupUi(self, DefaultMain):
        DefaultMain.setObjectName("DefaultMain")
        DefaultMain.resize(693, 600)
        self.centralwidget = QtWidgets.QWidget(DefaultMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.widgetTabs.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widgetTabs.setObjectName("widgetTabs")
        self.verticalLayout_2.addWidget(self.widgetTabs)
        DefaultMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DefaultMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuPaPI = QtWidgets.QMenu(self.menubar)
        self.menuPaPI.setObjectName("menuPaPI")
        self.menuPlugin = QtWidgets.QMenu(self.menubar)
        self.menuPlugin.setObjectName("menuPlugin")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DefaultMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DefaultMain)
        self.statusbar.setObjectName("statusbar")
        DefaultMain.setStatusBar(self.statusbar)
        self.toolbar = PaPIToolbar(DefaultMain)
        self.toolbar.setAcceptDrops(True)
        self.toolbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolbar.setMovable(False)
        self.toolbar.setFloatable(False)
        self.toolbar.setObjectName("toolbar")
        DefaultMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.action_load_config = QtWidgets.QAction(DefaultMain)
        self.action_load_config.setObjectName("action_load_config")
        self.action_save_config = QtWidgets.QAction(DefaultMain)
        self.action_save_config.setObjectName("action_save_config")
        self.action_open_overview_menu = QtWidgets.QAction(DefaultMain)
        self.action_open_overview_menu.setObjectName("action_open_overview_menu")
        self.action_open_create_plugin_menu = QtWidgets.QAction(DefaultMain)
        self.action_open_create_plugin_menu.setObjectName("action_open_create_plugin_menu")
        self.action_exit = QtWidgets.QAction(DefaultMain)
        self.action_exit.setObjectName("action_exit")
        self.action_reload_config = QtWidgets.QAction(DefaultMain)
        self.action_reload_config.setObjectName("action_reload_config")
        self.action_reset_papi = QtWidgets.QAction(DefaultMain)
        self.action_reset_papi.setObjectName("action_reset_papi")
        self.action_toggle_run_mode = QtWidgets.QAction(DefaultMain)
        self.action_toggle_run_mode.setObjectName("action_toggle_run_mode")
        self.actionSetBackground = QtWidgets.QAction(DefaultMain)
        self.actionSetBackground.setObjectName("actionSetBackground")
        self.action_open_papi_wiki = QtWidgets.QAction(DefaultMain)
        self.action_open_papi_wiki.setObjectName("action_open_papi_wiki")
        self.action_open_papi_doc = QtWidgets.QAction(DefaultMain)
        self.action_open_papi_doc.setObjectName("action_open_papi_doc")
        self.action_open_papi_about = QtWidgets.QAction(DefaultMain)
        self.action_open_papi_about.setObjectName("action_open_papi_about")
        self.action_open_qt_about = QtWidgets.QAction(DefaultMain)
        self.action_open_qt_about.setObjectName("action_open_qt_about")
        self.actionAbout_PySide = QtWidgets.QAction(DefaultMain)
        self.actionAbout_PySide.setObjectName("actionAbout_PySide")
        self.action_reload_plugin_db = QtWidgets.QAction(DefaultMain)
        self.action_reload_plugin_db.setObjectName("action_reload_plugin_db")
        self.action_toggle_toolbar = QtWidgets.QAction(DefaultMain)
        self.action_toggle_toolbar.setCheckable(True)
        self.action_toggle_toolbar.setChecked(True)
        self.action_toggle_toolbar.setObjectName("action_toggle_toolbar")
        self.actionFullscreen = QtWidgets.QAction(DefaultMain)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.menuPaPI.addAction(self.action_load_config)
        self.menuPaPI.addAction(self.action_save_config)
        self.menuPaPI.addAction(self.action_reload_config)
        self.menuPaPI.addAction(self.action_reset_papi)
        self.menuPaPI.addSeparator()
        self.menuPaPI.addAction(self.action_exit)
        self.menuPlugin.addAction(self.action_open_create_plugin_menu)
        self.menuPlugin.addAction(self.action_open_overview_menu)
        self.menuPlugin.addSeparator()
        self.menuPlugin.addAction(self.action_reload_plugin_db)
        self.menuView.addAction(self.action_toggle_run_mode)
        self.menuView.addAction(self.action_toggle_toolbar)
        self.menuView.addAction(self.actionFullscreen)
        self.menuHelp.addAction(self.action_open_papi_wiki)
        self.menuHelp.addAction(self.action_open_papi_doc)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_open_papi_about)
        self.menuHelp.addAction(self.action_open_qt_about)
        self.menubar.addAction(self.menuPaPI.menuAction())
        self.menubar.addAction(self.menuPlugin.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolbar.addAction(self.action_load_config)
        self.toolbar.addAction(self.action_save_config)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_open_create_plugin_menu)
        self.toolbar.addAction(self.action_open_overview_menu)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_reset_papi)
        self.toolbar.addSeparator()

        self.retranslateUi(DefaultMain)
        self.widgetTabs.setCurrentIndex(-1)
        self.action_exit.triggered.connect(DefaultMain.close)
        QtCore.QMetaObject.connectSlotsByName(DefaultMain)

    def retranslateUi(self, DefaultMain):
        _translate = QtCore.QCoreApplication.translate
        DefaultMain.setWindowTitle(_translate("DefaultMain", "MainWindow"))
        self.menuPaPI.setTitle(_translate("DefaultMain", "PaPI"))
        self.menuPlugin.setTitle(_translate("DefaultMain", "Plugin"))
        self.menuView.setTitle(_translate("DefaultMain", "View"))
        self.menuHelp.setTitle(_translate("DefaultMain", "Help"))
        self.toolbar.setWindowTitle(_translate("DefaultMain", "toolBar"))
        self.action_load_config.setText(_translate("DefaultMain", "Load"))
        self.action_save_config.setText(_translate("DefaultMain", "Save"))
        self.action_open_overview_menu.setText(_translate("DefaultMain", "Overview"))
        self.action_open_create_plugin_menu.setText(_translate("DefaultMain", "Create"))
        self.action_exit.setText(_translate("DefaultMain", "Exit"))
        self.action_reload_config.setText(_translate("DefaultMain", "ReloadConfig"))
        self.action_reset_papi.setText(_translate("DefaultMain", "ResetPaPI"))
        self.action_toggle_run_mode.setText(_translate("DefaultMain", "RunMode"))
        self.actionSetBackground.setText(_translate("DefaultMain", "SetBackground"))
        self.action_open_papi_wiki.setText(_translate("DefaultMain", "PaPI Wiki"))
        self.action_open_papi_doc.setText(_translate("DefaultMain", "PaPI Doc"))
        self.action_open_papi_about.setText(_translate("DefaultMain", "About"))
        self.action_open_qt_about.setText(_translate("DefaultMain", "About Qt"))
        self.actionAbout_PySide.setText(_translate("DefaultMain", "About PySide"))
        self.action_reload_plugin_db.setText(_translate("DefaultMain", "Reload DB"))
        self.action_toggle_toolbar.setText(_translate("DefaultMain", "Toolbar"))
        self.actionFullscreen.setText(_translate("DefaultMain", "Fullscreen"))

from papi.gui.default.item import PaPIToolbar
