# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui/default/DefaultMain.ui'
#
# Created: Wed Dec 16 14:32:09 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DefaultMain(object):
    def setupUi(self, DefaultMain):
        DefaultMain.setObjectName("DefaultMain")
        DefaultMain.resize(693, 600)
        self.centralwidget = QtWidgets.QWidget(DefaultMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.widgetTabs.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widgetTabs.setObjectName("widgetTabs")
        self.verticalLayout_2.addWidget(self.widgetTabs)
        DefaultMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DefaultMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuPaPI = QtWidgets.QMenu(self.menubar)
        self.menuPaPI.setObjectName("menuPaPI")
        self.menuPlugin = QtWidgets.QMenu(self.menubar)
        self.menuPlugin.setObjectName("menuPlugin")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DefaultMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DefaultMain)
        self.statusbar.setObjectName("statusbar")
        DefaultMain.setStatusBar(self.statusbar)
        self.toolBar = PaPIToolbar(DefaultMain)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        DefaultMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtWidgets.QAction(DefaultMain)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(DefaultMain)
        self.actionSave.setObjectName("actionSave")
        self.actionOverview = QtWidgets.QAction(DefaultMain)
        self.actionOverview.setObjectName("actionOverview")
        self.actionCreate = QtWidgets.QAction(DefaultMain)
        self.actionCreate.setObjectName("actionCreate")
        self.actionExit = QtWidgets.QAction(DefaultMain)
        self.actionExit.setObjectName("actionExit")
        self.actionReloadConfig = QtWidgets.QAction(DefaultMain)
        self.actionReloadConfig.setObjectName("actionReloadConfig")
        self.actionResetPaPI = QtWidgets.QAction(DefaultMain)
        self.actionResetPaPI.setObjectName("actionResetPaPI")
        self.actionRunMode = QtWidgets.QAction(DefaultMain)
        self.actionRunMode.setObjectName("actionRunMode")
        self.actionSetBackground = QtWidgets.QAction(DefaultMain)
        self.actionSetBackground.setObjectName("actionSetBackground")
        self.actionPaPI_Wiki = QtWidgets.QAction(DefaultMain)
        self.actionPaPI_Wiki.setObjectName("actionPaPI_Wiki")
        self.actionPaPI_Doc = QtWidgets.QAction(DefaultMain)
        self.actionPaPI_Doc.setObjectName("actionPaPI_Doc")
        self.actionAbout = QtWidgets.QAction(DefaultMain)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(DefaultMain)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_PySide = QtWidgets.QAction(DefaultMain)
        self.actionAbout_PySide.setObjectName("actionAbout_PySide")
        self.actionReload_Plugin_DB = QtWidgets.QAction(DefaultMain)
        self.actionReload_Plugin_DB.setObjectName("actionReload_Plugin_DB")
        self.actionToolbar = QtWidgets.QAction(DefaultMain)
        self.actionToolbar.setCheckable(True)
        self.actionToolbar.setChecked(True)
        self.actionToolbar.setObjectName("actionToolbar")
        self.menuPaPI.addAction(self.actionLoad)
        self.menuPaPI.addAction(self.actionSave)
        self.menuPaPI.addAction(self.actionReloadConfig)
        self.menuPaPI.addAction(self.actionResetPaPI)
        self.menuPaPI.addSeparator()
        self.menuPaPI.addAction(self.actionExit)
        self.menuPlugin.addAction(self.actionCreate)
        self.menuPlugin.addAction(self.actionOverview)
        self.menuPlugin.addSeparator()
        self.menuPlugin.addAction(self.actionReload_Plugin_DB)
        self.menuView.addAction(self.actionRunMode)
        self.menuView.addAction(self.actionToolbar)
        self.menuHelp.addAction(self.actionPaPI_Wiki)
        self.menuHelp.addAction(self.actionPaPI_Doc)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuPaPI.menuAction())
        self.menubar.addAction(self.menuPlugin.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate)
        self.toolBar.addAction(self.actionOverview)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionResetPaPI)
        self.toolBar.addSeparator()

        self.retranslateUi(DefaultMain)
        self.widgetTabs.setCurrentIndex(-1)
        self.actionExit.triggered.connect(DefaultMain.close)
        QtCore.QMetaObject.connectSlotsByName(DefaultMain)

    def retranslateUi(self, DefaultMain):
        _translate = QtCore.QCoreApplication.translate
        DefaultMain.setWindowTitle(_translate("DefaultMain", "MainWindow"))
        self.menuPaPI.setTitle(_translate("DefaultMain", "PaPI"))
        self.menuPlugin.setTitle(_translate("DefaultMain", "Plugin"))
        self.menuView.setTitle(_translate("DefaultMain", "View"))
        self.menuHelp.setTitle(_translate("DefaultMain", "Help"))
        self.toolBar.setWindowTitle(_translate("DefaultMain", "toolBar"))
        self.actionLoad.setText(_translate("DefaultMain", "Load"))
        self.actionSave.setText(_translate("DefaultMain", "Save"))
        self.actionOverview.setText(_translate("DefaultMain", "Overview"))
        self.actionCreate.setText(_translate("DefaultMain", "Create"))
        self.actionExit.setText(_translate("DefaultMain", "Exit"))
        self.actionReloadConfig.setText(_translate("DefaultMain", "ReloadConfig"))
        self.actionResetPaPI.setText(_translate("DefaultMain", "ResetPaPI"))
        self.actionRunMode.setText(_translate("DefaultMain", "RunMode"))
        self.actionSetBackground.setText(_translate("DefaultMain", "SetBackground"))
        self.actionPaPI_Wiki.setText(_translate("DefaultMain", "PaPI Wiki"))
        self.actionPaPI_Doc.setText(_translate("DefaultMain", "PaPI Doc"))
        self.actionAbout.setText(_translate("DefaultMain", "About"))
        self.actionAbout_Qt.setText(_translate("DefaultMain", "About Qt"))
        self.actionAbout_PySide.setText(_translate("DefaultMain", "About PySide"))
        self.actionReload_Plugin_DB.setText(_translate("DefaultMain", "Reload DB"))
        self.actionToolbar.setText(_translate("DefaultMain", "Toolbar"))

from papi.gui.default.item import PaPIToolbar
