# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui/default/PluginCreateMenu.ui'
#
# Created: Wed Sep 23 16:43:03 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PluginCreateMenu(object):
    def setupUi(self, PluginCreateMenu):
        PluginCreateMenu.setObjectName("PluginCreateMenu")
        PluginCreateMenu.resize(742, 629)
        self.centralwidget = QtWidgets.QWidget(PluginCreateMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pluginTree = QtWidgets.QTreeView(self.centralwidget)
        self.pluginTree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.pluginTree.setObjectName("pluginTree")
        self.pluginTree.header().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.pluginTree)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pluginSearchText = QtWidgets.QLineEdit(self.centralwidget)
        self.pluginSearchText.setObjectName("pluginSearchText")
        self.horizontalLayout_4.addWidget(self.pluginSearchText)
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_4.addWidget(self.helpButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 356, 585))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.authorLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.authorLabel.setObjectName("authorLabel")
        self.verticalLayout.addWidget(self.authorLabel)
        self.authorEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.authorEdit.setReadOnly(True)
        self.authorEdit.setObjectName("authorEdit")
        self.verticalLayout.addWidget(self.authorEdit)
        self.pathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout.addWidget(self.pathLabel)
        self.pathEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.pathEdit.setReadOnly(True)
        self.pathEdit.setObjectName("pathEdit")
        self.verticalLayout.addWidget(self.pathEdit)
        self.descriptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.descriptionText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.descriptionText.setReadOnly(True)
        self.descriptionText.setObjectName("descriptionText")
        self.verticalLayout.addWidget(self.descriptionText)
        self.modulesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.modulesLabel.setObjectName("modulesLabel")
        self.verticalLayout.addWidget(self.modulesLabel)
        self.modulesList = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.modulesList.setObjectName("modulesList")
        self.verticalLayout.addWidget(self.modulesList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.createButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout_3.addWidget(self.createButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        PluginCreateMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PluginCreateMenu)
        self.statusbar.setObjectName("statusbar")
        PluginCreateMenu.setStatusBar(self.statusbar)

        self.retranslateUi(PluginCreateMenu)
        QtCore.QMetaObject.connectSlotsByName(PluginCreateMenu)

    def retranslateUi(self, PluginCreateMenu):
        _translate = QtCore.QCoreApplication.translate
        PluginCreateMenu.setWindowTitle(_translate("PluginCreateMenu", "MainWindow"))
        self.pluginSearchText.setPlaceholderText(_translate("PluginCreateMenu", "Search for ..."))
        self.helpButton.setText(_translate("PluginCreateMenu", "Help"))
        self.nameLabel.setText(_translate("PluginCreateMenu", "Name"))
        self.authorLabel.setText(_translate("PluginCreateMenu", "Author"))
        self.pathLabel.setText(_translate("PluginCreateMenu", "Path"))
        self.descriptionLabel.setText(_translate("PluginCreateMenu", "Description"))
        self.modulesLabel.setText(_translate("PluginCreateMenu", "Missing Modules"))
        self.createButton.setText(_translate("PluginCreateMenu", "Create Plugin"))

