# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui/qt_new/main.ui'
#
# Created: Fri Apr 24 15:30:18 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QtNewMain(object):
    def setupUi(self, QtNewMain):
        QtNewMain.setObjectName("QtNewMain")
        QtNewMain.resize(693, 600)
        self.centralwidget = QtWidgets.QWidget(QtNewMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widgetTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.widgetTabs.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widgetTabs.setObjectName("widgetTabs")
        self.verticalLayout_2.addWidget(self.widgetTabs)
        QtNewMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QtNewMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuPaPI = QtWidgets.QMenu(self.menubar)
        self.menuPaPI.setObjectName("menuPaPI")
        self.menuPlugin = QtWidgets.QMenu(self.menubar)
        self.menuPlugin.setObjectName("menuPlugin")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        QtNewMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QtNewMain)
        self.statusbar.setObjectName("statusbar")
        QtNewMain.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(QtNewMain)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(QtNewMain)
        self.actionSave.setObjectName("actionSave")
        self.actionOverview = QtWidgets.QAction(QtNewMain)
        self.actionOverview.setObjectName("actionOverview")
        self.actionCreate = QtWidgets.QAction(QtNewMain)
        self.actionCreate.setObjectName("actionCreate")
        self.actionExit = QtWidgets.QAction(QtNewMain)
        self.actionExit.setObjectName("actionExit")
        self.actionReloadConfig = QtWidgets.QAction(QtNewMain)
        self.actionReloadConfig.setObjectName("actionReloadConfig")
        self.actionResetPaPI = QtWidgets.QAction(QtNewMain)
        self.actionResetPaPI.setObjectName("actionResetPaPI")
        self.actionRunMode = QtWidgets.QAction(QtNewMain)
        self.actionRunMode.setObjectName("actionRunMode")
        self.actionSetBackground = QtWidgets.QAction(QtNewMain)
        self.actionSetBackground.setObjectName("actionSetBackground")
        self.actionPaPI_Wiki = QtWidgets.QAction(QtNewMain)
        self.actionPaPI_Wiki.setObjectName("actionPaPI_Wiki")
        self.actionPaPI_Doc = QtWidgets.QAction(QtNewMain)
        self.actionPaPI_Doc.setObjectName("actionPaPI_Doc")
        self.actionAbout = QtWidgets.QAction(QtNewMain)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(QtNewMain)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_PySide = QtWidgets.QAction(QtNewMain)
        self.actionAbout_PySide.setObjectName("actionAbout_PySide")
        self.actionReload_Plugin_DB = QtWidgets.QAction(QtNewMain)
        self.actionReload_Plugin_DB.setObjectName("actionReload_Plugin_DB")
        self.menuPaPI.addAction(self.actionLoad)
        self.menuPaPI.addAction(self.actionSave)
        self.menuPaPI.addAction(self.actionReloadConfig)
        self.menuPaPI.addAction(self.actionResetPaPI)
        self.menuPaPI.addSeparator()
        self.menuPaPI.addAction(self.actionExit)
        self.menuPlugin.addAction(self.actionOverview)
        self.menuPlugin.addAction(self.actionCreate)
        self.menuPlugin.addSeparator()
        self.menuPlugin.addAction(self.actionReload_Plugin_DB)
        self.menuView.addAction(self.actionRunMode)
        self.menuHelp.addAction(self.actionPaPI_Wiki)
        self.menuHelp.addAction(self.actionPaPI_Doc)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuPaPI.menuAction())
        self.menubar.addAction(self.menuPlugin.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(QtNewMain)
        self.widgetTabs.setCurrentIndex(-1)
        self.actionExit.triggered.connect(QtNewMain.close)
        QtCore.QMetaObject.connectSlotsByName(QtNewMain)

    def retranslateUi(self, QtNewMain):
        _translate = QtCore.QCoreApplication.translate
        QtNewMain.setWindowTitle(_translate("QtNewMain", "MainWindow"))
        self.loadButton.setText(_translate("QtNewMain", "Load"))
        self.saveButton.setText(_translate("QtNewMain", "Save"))
        self.menuPaPI.setTitle(_translate("QtNewMain", "PaPI"))
        self.menuPlugin.setTitle(_translate("QtNewMain", "Plugin"))
        self.menuView.setTitle(_translate("QtNewMain", "View"))
        self.menuHelp.setTitle(_translate("QtNewMain", "Help"))
        self.actionLoad.setText(_translate("QtNewMain", "Load"))
        self.actionSave.setText(_translate("QtNewMain", "Save"))
        self.actionOverview.setText(_translate("QtNewMain", "Overview"))
        self.actionCreate.setText(_translate("QtNewMain", "Create"))
        self.actionExit.setText(_translate("QtNewMain", "Exit"))
        self.actionReloadConfig.setText(_translate("QtNewMain", "ReloadConfig"))
        self.actionResetPaPI.setText(_translate("QtNewMain", "ResetPaPI"))
        self.actionRunMode.setText(_translate("QtNewMain", "RunMode"))
        self.actionSetBackground.setText(_translate("QtNewMain", "SetBackground"))
        self.actionPaPI_Wiki.setText(_translate("QtNewMain", "PaPI Wiki"))
        self.actionPaPI_Doc.setText(_translate("QtNewMain", "PaPI Doc"))
        self.actionAbout.setText(_translate("QtNewMain", "About"))
        self.actionAbout_Qt.setText(_translate("QtNewMain", "About Qt"))
        self.actionAbout_PySide.setText(_translate("QtNewMain", "About PySide"))
        self.actionReload_Plugin_DB.setText(_translate("QtNewMain", "Reload DB"))

