# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui/qt_new/overview.ui'
#
# Created: Thu Jul  2 15:35:54 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Overview(object):
    def setupUi(self, Overview):
        Overview.setObjectName("Overview")
        Overview.resize(803, 614)
        self.centralwidget = QtWidgets.QWidget(Overview)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pluginTree = QtWidgets.QTreeView(self.centralwidget)
        self.pluginTree.setObjectName("pluginTree")
        self.horizontalLayout.addWidget(self.pluginTree)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pluginTab = QtWidgets.QWidget()
        self.pluginTab.setObjectName("pluginTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pluginTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.unameLabel = QtWidgets.QLabel(self.pluginTab)
        self.unameLabel.setObjectName("unameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.unameLabel)
        self.unameEdit = QtWidgets.QLineEdit(self.pluginTab)
        self.unameEdit.setObjectName("unameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.unameEdit)
        self.usedpluginLabel = QtWidgets.QLabel(self.pluginTab)
        self.usedpluginLabel.setObjectName("usedpluginLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.usedpluginLabel)
        self.usedpluginEdit = QtWidgets.QLineEdit(self.pluginTab)
        self.usedpluginEdit.setObjectName("usedpluginEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.usedpluginEdit)
        self.stateLabel = QtWidgets.QLabel(self.pluginTab)
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stateLabel)
        self.stateEdit = QtWidgets.QLineEdit(self.pluginTab)
        self.stateEdit.setObjectName("stateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stateEdit)
        self.typeLabel = QtWidgets.QLabel(self.pluginTab)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.typeEdit = QtWidgets.QLineEdit(self.pluginTab)
        self.typeEdit.setObjectName("typeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.typeEdit)
        self.alivestateLabel = QtWidgets.QLabel(self.pluginTab)
        self.alivestateLabel.setObjectName("alivestateLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.alivestateLabel)
        self.alivestateEdit = QtWidgets.QLineEdit(self.pluginTab)
        self.alivestateEdit.setObjectName("alivestateEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.alivestateEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.pluginTab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.parameterTab = QtWidgets.QWidget()
        self.parameterTab.setObjectName("parameterTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.parameterTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.parameterTree = QtWidgets.QTreeView(self.parameterTab)
        self.parameterTree.setObjectName("parameterTree")
        self.verticalLayout_4.addWidget(self.parameterTree)
        self.tabWidget_2.addTab(self.parameterTab, "")
        self.blockTab = QtWidgets.QWidget()
        self.blockTab.setObjectName("blockTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.blockTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.showInternalNameCheckBox = QtWidgets.QCheckBox(self.blockTab)
        self.showInternalNameCheckBox.setObjectName("showInternalNameCheckBox")
        self.verticalLayout_5.addWidget(self.showInternalNameCheckBox)
        self.blockTree = QtWidgets.QTreeView(self.blockTab)
        self.blockTree.setObjectName("blockTree")
        self.verticalLayout_5.addWidget(self.blockTree)
        self.tabWidget_2.addTab(self.blockTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pauseButton = QtWidgets.QPushButton(self.pluginTab)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_2.addWidget(self.pauseButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stopButton = QtWidgets.QPushButton(self.pluginTab)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.playButton = QtWidgets.QPushButton(self.pluginTab)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_2.addWidget(self.playButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.pluginTab, "")
        self.connectionTab = QtWidgets.QWidget()
        self.connectionTab.setObjectName("connectionTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.connectionTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.subscribersTree = QtWidgets.QTreeView(self.connectionTab)
        self.subscribersTree.setObjectName("subscribersTree")
        self.verticalLayout.addWidget(self.subscribersTree)
        self.subscriptionsTree = QtWidgets.QTreeView(self.connectionTab)
        self.subscriptionsTree.setObjectName("subscriptionsTree")
        self.verticalLayout.addWidget(self.subscriptionsTree)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.connectionTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        Overview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Overview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 25))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        Overview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Overview)
        self.statusbar.setObjectName("statusbar")
        Overview.setStatusBar(self.statusbar)
        self.actionRefresh = QtWidgets.QAction(Overview)
        self.actionRefresh.setObjectName("actionRefresh")
        self.menuAction.addAction(self.actionRefresh)
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(Overview)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Overview)

    def retranslateUi(self, Overview):
        _translate = QtCore.QCoreApplication.translate
        Overview.setWindowTitle(_translate("Overview", "MainWindow"))
        self.unameLabel.setText(_translate("Overview", "Unique name"))
        self.usedpluginLabel.setText(_translate("Overview", "Used plugin"))
        self.stateLabel.setText(_translate("Overview", "State"))
        self.typeLabel.setText(_translate("Overview", "Type"))
        self.alivestateLabel.setText(_translate("Overview", "Alive state"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.parameterTab), _translate("Overview", "Parameters"))
        self.showInternalNameCheckBox.setText(_translate("Overview", "Show internal signal names"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.blockTab), _translate("Overview", "Blocks"))
        self.pauseButton.setText(_translate("Overview", "PAUSE"))
        self.stopButton.setText(_translate("Overview", "STOP"))
        self.playButton.setText(_translate("Overview", "PLAY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginTab), _translate("Overview", "Plugin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connectionTab), _translate("Overview", "Connections"))
        self.menuAction.setTitle(_translate("Overview", "Actions"))
        self.actionRefresh.setText(_translate("Overview", "Refresh"))

